[Mission 01] feat: initialize project
ssoyeong/spring-boot-study pull request #2
Opened 2023-10-01 06:33 UTC by ssoyeong

# 미션
[Spring Initializr](https://start.spring.io/)로 스프링 부트 프로젝트를 세팅하기

# 세부 내용
- [x] 빌드 툴은 Gradle을 이용하고 빌드 스크립트는 Kotlin을 선택한다.
- [x] 언어는 Java를 선택한다. 버전은 JDK17
- [x] 스프링 부트 버전은 최신 GA 버전을 선택한다.
- [x] 패키징은 Jar

# 공부 포인트
[[Spring Boot] 1. 스프링 부트 프로젝트 만들기](https://ssoyeong.tistory.com/51)

# 배운 점
이전까지 아무 생각 없이 Spring Initializr에서 스프링 부트 프로젝트를 만들어 왔는데, 내가 어떤 설정으로 프로젝트를 만든 것인지 명확하게 이해하고 셋팅할 수 있었다.

2023-10-01 08:46 UTC, doljae requested changes
첫 미션 고생하셨습니다 🙁 

몇 가지 포인트에 대해서 코멘트 드립니다.

### 1. 이번에 만든 프로젝트 디렉터리 깊이를 1단계 올려주세요.

- AS-IS: `/spring-boot-study/first-mission`
- TO-BE: `/first-mission`

앞으로의 미션에서는 이번에 만든 프로젝트에 살을 붙이는 식으로 작업할 예정입니다. 그래서 repository 디렉터리 내부에 프로젝트 디렉터리를 만드는 것이 아닌 repository 자체가 프로젝트가 되게 조정해주세요.

### 2. `FirstMission` 대신 `SpringBootStudyApplication` 혹은 `StudyApplication`으로 이름을 변경해주세요.

1번 포인트와 연관된 내용으로 범용적으로 사용할 수 있는 이름으로 변경해주세요.
repository 이름이 `spring-boot-study` 여서 예시로 제안 드린 이름이고 다른 이름도 괜찮습니다.

알고 계시겠지만 미션 단위로 어떤 작업을 했는지는 git log 혹은 PR history 등으로도 확인할 수 있습니다.

2023-10-01 08:47 UTC, doljae commented on first-mission/src/main/java/com/ssoyeong/firstmission/FirstMissionApplication.java
> +package com.ssoyeong.firstmission;
✅

2023-10-01 08:47 UTC, doljae commented
> 첫 미션 고생하셨습니다 🙁
> 
> 몇 가지 포인트에 대해서 코멘트 드립니다.
> 
> ### 1. 이번에 만든 프로젝트 디렉터리 깊이를 1단계 올려주세요.
> * AS-IS: `/spring-boot-study/first-mission`
> * TO-BE: `/first-mission`
> 
> 앞으로의 미션에서는 이번에 만든 프로젝트에 살을 붙이는 식으로 작업할 예정입니다. 그래서 repository 디렉터리 내부에 프로젝트 디렉터리를 만드는 것이 아닌 repository 자체가 프로젝트가 되게 조정해주세요.
> 
> ### 2. `FirstMission` 대신 `SpringBootStudyApplication` 혹은 `StudyApplication`으로 이름을 변경해주세요.
> 1번 포인트와 연관된 내용으로 범용적으로 사용할 수 있는 이름으로 변경해주세요. repository 이름이 `spring-boot-study` 여서 예시로 제안 드린 이름이고 다른 이름도 괜찮습니다.
> 
> 알고 계시겠지만 미션 단위로 어떤 작업을 했는지는 git log 혹은 PR history 등으로도 확인할 수 있습니다.
> 
> 적용해야 하는 부분에 추가로 코멘트 남겨두겠습니다~

2023-10-01 08:49 UTC, doljae commented
수정 목록

- [ ] 클래스 이름
- [ ] 패키지 이름
- [ ] 모듈 이름
- [ ] 프로젝트 디렉터리 깊이

2023-10-01 08:55 UTC, doljae commented
<img width="332" alt="스크린샷 2023-10-01 오후 5 55 25" src="https://github.com/ssoyeong/spring-boot-study/assets/37795866/9bff8239-f325-4cb5-84f5-3063f9097289">


그리고 PR을 만들고 난 뒤에 이 PR과 연결된 Issue도 링크해주시면 이 PR이 merge 되었을 때 이슈도 함께 closed 처리 됩니다~

2023-10-05 10:13 UTC, ssoyeong commented
# 추가 작업
- [ ] 클래스 이름
- [ ] 패키지 이름
- [ ] 모듈 이름
- [x] 프로젝트 디렉터리 깊이
- [x] 프로젝트 재생성

`study-application` 이름으로 프로젝트를 다시 만들었습니다.
이름을 수정해도 반영 안되는 부분들이 계속 나오더라구요🥲

2023-10-05 12:29 UTC, doljae approved these changes

2023-10-05 12:29 UTC, doljae commented
LGTM 👍

2023-10-05 13:21 UTC, merged